apiVersion: storage.halo.run/v1alpha1
kind: PolicyTemplate
metadata:
  # used to determine whether a file should be handled by us
  name: chenhe-lsky-pro
spec:
  displayName: Lsky Pro 兰空图床
  settingName: chenhe-lsky-pro-policy-template-setting
---

apiVersion: v1alpha1
kind: Setting
metadata:
  name: chenhe-lsky-pro-policy-template-setting
spec:
  forms:
    - group: default
      formSchema:
        - $formkit: url
          name: lskyUrl
          label: Lsky Pro 地址
          help: "Lsky Pro 图床地址，必须以 http(s):// 开头，无需添加 '/' 或 api 后缀。"
          placeholder: "https://img.example.com"
          validation: required|url
          validation-visibility: live
        - $formkit: text
          name: lskyToken
          label: API Token
          help: '格式类似 Bearer x|xxxxxxx。留空则以游客身份上传。'
          placeholder: "Bearer  x|xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
          validation: [ [ 'matches', '/^Bearer \d+\|\w+$/' ] ]
          validation-visibility: live
        - $formkit: number
          name: lskyStrategy
          label: Lsky Pro 储存策略
          help: '可选。用于指定 Lsky Pro 储存策略 ID，对应 strategy_id 参数。只能输入整数，留空为默认。'
          validation: 'min:0'
        - $formkit: text
          name: instanceId
          label: 实例 ID
          help: "可选。用于重装插件或 Lsky Pro 地址变更时保持已上传附件的关联状态。与此值匹配的附件视为由此存储策略管理。中途修改将导致之前上传的图片无法关联到 LskyPro。留空默认使用图床地址。"
          validation: [ [ 'matches', '/^[\w-]+$/' ] ]
          validation-visibility: live
          validation-messages:
            matches: "仅支持字母、数字、下划线 '_' 与短横线 '-'。"
        - $el: 'p'
          attrs:
            style: { padding-top: '10px' }
          children: '提示：受限于 Lsky Pro，本插件仅支持图片类型的附件。'